import Head from "next/head";
import Image from "next/image";
import LandingUI from "../components/layoutComponents/LandingUI";
import About from "../components/layoutComponents/About";
import Products from "../components/layoutComponents/Products";
import Footer from "../components/layoutComponents/Footer";
import Deference from "../components/layoutComponents/Deference";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500&display=swap"
          rel="stylesheet"
        ></link>
      </Head>

      {/* Navbar */}
      <nav
        className="navbar navbar-expand-lg fixed-top"
        style={{ backgroundColor: "#FFF", height: "80px" }}
      >
        <div className="container-fluid">
          <Link className="navbar-brand" href="/">
            <Image
              src="/images/XYZlogo.png"
              alt="XYZ teas logo"
              width={120}
              height={60}
            />
          </Link>
          <button
            className="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span className="navbar-toggler-icon"></span>
          </button>
          <div className="collapse navbar-collapse" id="navbarNav">
            <div className="mx-auto"></div>
            <ul className="navbar-nav p-3">
              <li className="nav-item">
                <Link aria-current="page" href="#section-1">
                  <a className="nav-link active">HOME</a>
                </Link>
              </li>
              <li className="nav-item">
                <Link className="nav-link " href="#section-2">
                  <a className="nav-link active">PRODUCTS</a>
                </Link>
              </li>
              <li className="nav-item">
                <Link className="nav-link" href="#section-3">
                  <a className="nav-link active">ABOUT</a>
                </Link>
              </li>
              <li className="nav-item">
                <Link className="nav-link" href="#section-4">
                  <a className="nav-link active">OUR SERVICES</a>
                </Link>
              </li>
              <li className="nav-item">
                <Link className="nav-link" href="#section-5">
                  <a className="nav-link active">CONTACT</a>
                </Link>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      {/* Sections scrolling */}
      <section id="section-1">
        <LandingUI />
      </section>
      <section id="section-2">
        <Products />
      </section>
      <section id="section-3">
        <About />
      </section>
      <section id="section-4">
        <Deference />
      </section>
      <section id="section-5">
        <Footer />
      </section>
    </div>
  );
}
